[theme]
# Base Theme (light or dark)
base = "light"

## Modern Tech March Madness ##
primaryColor = "#66FCF1"  # Bright Teal (Dynamic, modern primary)
backgroundColor = "#1A1A1D" # Space Black (Sleek, dark background)
secondaryBackgroundColor = "#2C3531" # Space Gray (Subtle secondary background)
textColor = "#EEFCF7" # White Silver (Soft, readable text)
font = "sans serif"

# Dark Mode Specific Overrides
[theme.dark]
primaryColor = "#2BDB6B" # Alien Green (Vibrant primary in dark mode)
backgroundColor = "#121212" # Very Dark Gray (Deeper dark background)
secondaryBackgroundColor = "#19181A" # Space Black (Dark secondary background)
textColor = "#DADADA" # Football White (Readable text in dark mode)

# Component Styling (Fine-Grained Control)
[theme.components]
# Buttons
button = { primaryColor = "#66FCF1", textColor = "#1A1A1D", borderRadius = "25px", padding = "12px 25px", fontWeight = "600", boxShadow = "0 4px 8px rgba(0, 0, 0, 0.3)", border = "1px solid transparent" }
# Slider
slider = { primaryColor = "#66FCF1", trackColor = "#2C3531", thumbColor = "#66FCF1", trackHeight = "6px", thumbSize = "18px" }
# Selectbox
selectbox = { borderColor = "#2C3531", borderRadius = "25px", padding = "10px", focusBorderColor = "#66FCF1" }
# Text Input
textInput = { borderColor = "#2C3531", borderRadius = "25px", padding = "10px", focusBorderColor = "#66FCF1" }
# Expander
expander = { borderColor = "#2C3531", borderRadius = "25px", border = "1px solid #2C3531"}

# Font Customization (Advanced)
[theme.fonts]
bodyFont = "Roboto, sans-serif"
headingFont = "Montserrat, sans-serif"
monospaceFont = "Fira Mono, monospace"

# Layout and Spacing
[layout]
wideMode = true
spacing = "large"
padding = "1.5rem"


## HARDWOOD THEME ##
#primaryColor="#DADADA"
#backgroundColor= "#1A1A1D" #"" #hardwoodlightbrown attempts: #"#E9D0AF" #E4C49B  #DEB887 
#secondaryBackgroundColor="#DADADA"
#textColor= "#FFFFFF"
#font="sans serif"

## COLOR LIBRARY ##

#metallic-gold:"#D4AF37"
#dark-blue2:"#152238"
#dark-blue-OG:"#001440"
#dark-black: "#1B1E1F"
#space-black: "#1A1A1D"
#space-black2: "#17252A"
#space-black3: "#19181A"
#space-gray:"#282828"
#space-gray2: "#2C3531"
#LIGHT-BROWN: "#DEB887"
# football-white: "#DADADA"
# football-brown: "#663831"
# football-gold: "#CBB67C"
# reit-gold: "#FFDF00"
# white-silver: '#EEFCF7'
# white-silver: '#E9EDED'
# riverbank "#00680A"
# grass-green "#009A17"
# ok-dark-green: "#586D3D"
#alien-green-OG: "#EDF5E1"
#alien-green2: "#2BDB6B"
#bright-teal: "#66FCF1"


## SPACE THEME ##
# primaryColor="#66FCF1"
# backgroundColor="#1A1A1D" #"#1B1E1F"
# secondaryBackgroundColor="#020202"
# textColor="#66FCF1"
# font="monospace"

## MIAMI VICE ##
# primaryColor="#07efdb"
# backgroundColor="#02619C"
# secondaryBackgroundColor="#0a0a0a"
# textColor="#c00ce4"
# font="sans serif"

## G+B ##
# primaryColor="#5CD895"
# backgroundColor="#05386B"
# secondaryBackgroundColor="#8EE4AF"
# textColor="#EDF5E1"
# font="monospace"
