[theme]
# Base Theme
base = "light"

# Main Theme - March Madness Basketball Inspired
primaryColor = "#FF6B00"          # Vibrant Orange (Basketball color)
backgroundColor = "#1A1A1D"        # Deep Court Black
secondaryBackgroundColor = "#2C2C34" # Subtle Dark Gray
textColor = "#F5F5F5"             # Bright White for readability
font = "sans serif"

# Dark Mode Specific Overrides
[theme.dark]
primaryColor = "#FF6B00"          # Consistent basketball orange
backgroundColor = "#121212"        # Deeper dark
secondaryBackgroundColor = "#232328" # Darker secondary
textColor = "#FFFFFF"             # Pure white for dark mode
