[theme]
# Base Theme
base = "light"

# Main Theme - March Madness Basketball Inspired
primaryColor = "#FF6B00"          # Vibrant Orange (Basketball color)
backgroundColor = "#1A1A1D"        # Deep Court Black
secondaryBackgroundColor = "#2C2C34" # Subtle Dark Gray
textColor = "#F5F5F5"             # Bright White for readability
font = "sans serif"

# Dark Mode Specific Overrides
[theme.dark]
primaryColor = "#FF6B00"          # Consistent basketball orange
backgroundColor = "#121212"        # Deeper dark
secondaryBackgroundColor = "#232328" # Darker secondary
textColor = "#FFFFFF"             # Pure white for dark mode

# Component Styling
[theme.components]
# Buttons - Styled like basketball
button = { 
    backgroundColor = "#FF6B00", 
    textColor = "#FFFFFF", 
    borderRadius = "25px", 
    padding = "12px 24px", 
    fontWeight = "600", 
    boxShadow = "0 4px 8px rgba(0, 0, 0, 0.3)",
    hoverColor = "#E05600"
}

# Slider - Court markings inspired
slider = { 
    primaryColor = "#FF6B00", 
    trackColor = "#3B3B44", 
    thumbColor = "#FF6B00", 
    trackHeight = "6px", 
    thumbSize = "18px" 
}

# Selectbox - Clean, modern look
selectbox = { 
    borderColor = "#3B3B44", 
    borderRadius = "8px", 
    padding = "10px", 
    focusBorderColor = "#FF6B00" 
}

# Text Input - Consistent with selectbox
textInput = { 
    borderColor = "#3B3B44", 
    borderRadius = "8px", 
    padding = "10px", 
    focusBorderColor = "#FF6B00" 
}

# Expander - Scoreboard-like appearance
expander = { 
    borderColor = "#3B3B44", 
    borderRadius = "8px", 
    backgroundColor = "#2C2C34",
    headerColor = "#FF6B00"
}

# DataFrames - Tournament bracket styling
dataFrame = {
    borderColor = "#3B3B44",
    rowEvenColor = "#2C2C34",
    rowOddColor = "#232328"
}

# Font Customization
[theme.fonts]
bodyFont = "Roboto, 'Open Sans', sans-serif"
headingFont = "Montserrat, 'Raleway', sans-serif"
monospaceFont = "Consolas, 'Courier New', monospace"

# Layout and Spacing
[layout]
wideMode = true
spacing = "comfortable"
maxWidth = "1200px"
padding = "1.5rem"

# Animation Settings
[animations]
enabled = true
duration = "300ms"